### ISSUE TITLE
如何运行您出版的 实战深度学习算法 第二章的mnist的例子

### ISSUE THREAD

**Issue by 459548764** [AskyJx/nn_base#1]
你好，请问你出版的书的第二章的例子运行的具体实例在仓库的哪里？可以详细给出吗？

**Comment by 459548764** [comment]
而且你的nn_base的代码 我这边根本跑不起来

ValueError: cannot reshape array of size 9912406 into shape (28873,784)
请指教谢谢

**Comment by AskyJx** [comment]
> 你好，请问你出版的书的第二章的例子运行的具体实例在仓库的哪里？可以详细给出吗？

你好，全书配套源码仓库此，在前言部分也有的仓库链接，谢谢你的反馈，请再试下可否访问，如有问题，欢迎在对应仓库下提issue：
https://github.com/AskyJx/xDeepLearningBook

**Comment by AskyJx** [comment]
> 而且你的nn_base的代码 我这边根本跑不起来
> 
> ValueError: cannot reshape array of size 9912406 into shape (28873,784)
> 请指教谢谢

请把完整异常信息（包含执行源码名）贴出来，这边查一下。

**Comment by 459548764** [comment]
友情提示，书本34页的softmax代码倒数第二行有明显错误，请注意印刷时更正。第二，个人认为MNIST直接这样单层去跑，92%的acc非常不可思议，我不确定你的acc是在train下得到的还是test上得到的，AUC曲线如何？这个第二章我个人认为需要认真严肃地改善。
 



------------------ 原始邮件 ------------------
发件人: "Jerry X"<notifications@github.com>; 
发送时间: 2019年9月8日(星期天) 晚上8:28
收件人: "AskyJx/nn_base"<nn_base@noreply.github.com>; 
抄送: "刘伟明"<459548764@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AskyJx/nn_base] 如何运行您出版的 实战深度学习算法 第二章的mnist的例子 (#1)



 
而且你的nn_base的代码 我这边根本跑不起来
 
ValueError: cannot reshape array of size 9912406 into shape (28873,784)
 请指教谢谢
  
请把完整异常信息（包含执行源码名）贴出来，这边查一下。

**Comment by AskyJx** [comment]
你好，书上34页softmax第16行exp_y这个变量应该为exp_z。非常感谢你指出这个错误，这边会加入勘误表，并在重印时请出版社协助更正。配套源码库的上的例子是可以正确运行的。
为便于同行使用源码库例子直接复现书中算法和观察结果，书中第36页给出了acc的定义：”accuracy=分类正确的样本个数/数据集样本总数“，以确保沟通理解的一致。
92%是独立验证集上的acc，EPOCH_NUM设置为10，ITERATIONTERATION设置5，您应该可以在1分钟得到这个结果。
再次感谢您的思考和反馈！
